# Generated by Django 3.2.6 on 2021-09-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210926_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='numero_fixo',
            field=models.CharField(default=None, help_text='Enter your number like: 0000000000, put your DDD', max_length=10, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='medic',
            name='whatsapp',
            field=models.CharField(default=None, help_text='Enter your number like: 0000000000, put your DDD and DDI', max_length=13, verbose_name='Whatsapp'),
        ),
    ]
