# Generated by Django 3.2.7 on 2021-10-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='valor_total',
            field=models.DecimalField(decimal_places=0, max_digits=30, verbose_name='Valor total'),
        ),
    ]
