# Generated by Django 3.2.6 on 2021-09-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Enter the name of Medic.', max_length=20, verbose_name='Name')),
                ('cpf', models.CharField(help_text='Enter only numbers.', max_length=11, verbose_name='CPF')),
                ('crm', models.CharField(help_text='Enter your 6 crm numbers.', max_length=6, verbose_name='CRM')),
                ('uf_crm', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO'), ('Distrito Federal', 'DF')], max_length=25, verbose_name='UF')),
                ('espec', models.CharField(max_length=255, verbose_name='Expertise')),
                ('estado', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO'), ('Distrito Federal', 'DF')], help_text='Enter which state you live in', max_length=30, verbose_name='State')),
                ('cidade', models.CharField(help_text='Enter which City you live in', max_length=30, verbose_name='City')),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(help_text='Enter the Agent email address.', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nome',
            field=models.CharField(help_text='Enter the name of Agent.', max_length=20, verbose_name='Name'),
        ),
    ]
