# Generated by Django 3.2.7 on 2021-10-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pipeline_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Aberto', 'Aberto'), ('Pendente', 'Pendente'), ('Fechado', 'Fechado')], default='Novo', max_length=255, verbose_name='Status'),
        ),
    ]
