# Generated by Django 3.2.7 on 2021-10-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pipeline_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='medico',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='prioridade',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto')], default='Baixo', max_length=255, verbose_name='Prioridade'),
        ),
    ]
