# Generated by Django 3.2.7 on 2021-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210926_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='cargo',
            field=models.CharField(choices=[('Administrador', 'ADM'), ('Diretor', 'DIRETOR'), ('Agente', 'AGENT')], default='Agente', max_length=13, verbose_name='Roles'),
        ),
    ]
