# Generated by Django 3.2.7 on 2021-10-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211005_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='cargo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('Diretor', 'DIRETOR'), ('Agente', 'AGENT')], default='Agente', max_length=13, verbose_name='Roles'),
        ),
    ]
