# Generated by Django 3.2.7 on 2021-10-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_permission_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='cargo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('Diretor', 'DIRETOR'), ('Agente', 'AGENT')], default='Agente', max_length=13, verbose_name='Roles'),
        ),
    ]
