# Generated by Django 3.2.7 on 2021-10-07 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Clinica', 'Clinica'), ('Hospital', 'Hospital'), ('Laboratório', 'Laboratório'), ('Agência de plano de Saúde', 'Agência de plano de Saúde')], max_length=100, verbose_name='Categoria')),
                ('razao', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('produto', models.CharField(choices=[('nMonitor', 'nMonitor'), ('nSensor', 'nSensor'), ('nCommand', 'nCommand'), ('nEcho', 'nEcho'), ('nReport', 'nR'), ('Iara', 'Iara')], max_length=100, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('crm', models.CharField(max_length=6, verbose_name='CRM')),
                ('uf_crm', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO'), ('Distrito Federal', 'DF')], max_length=25, verbose_name='UF')),
                ('espec', models.CharField(max_length=255, verbose_name='Especialidade')),
                ('estado', models.CharField(choices=[('Acre', 'AC'), ('Alagoas', 'AL'), ('Amapá', 'AP'), ('Amazonas', 'AM'), ('Bahia', 'BA'), ('Ceará', 'CE'), ('Espírito Santo', 'ES'), ('Goiás', 'GO'), ('Maranhão', 'MA'), ('Mato Grosso', 'MT'), ('Mato Grosso do Sul', 'MS'), ('Minas Gerais', 'MG'), ('Pará', 'PA'), ('Paraíba', 'PB'), ('Paraná', 'PR'), ('Pernambuco', 'PE'), ('Piauí', 'PI'), ('Rio de Janeiro', 'RJ'), ('Rio Grande do Norte', 'RN'), ('Rio Grande do Sul', 'RS'), ('Rondônia', 'RO'), ('Roraima', 'RR'), ('Santa Catarina', 'SC'), ('São Paulo', 'SP'), ('Sergipe', 'SE'), ('Tocantins', 'TO'), ('Distrito Federal', 'DF')], max_length=30, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
                ('numero_fixo', models.CharField(default=None, max_length=10, verbose_name='Telefone')),
                ('whatsapp', models.CharField(default=None, max_length=13, verbose_name='Whatsapp')),
                ('produto', models.CharField(choices=[('nReport', 'nR'), ('Iara', 'Iara')], max_length=255, verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Administrador', 'ADMINISTRADOR'), ('Diretor', 'DIRETOR'), ('Agente', 'AGENT')], default='Agente', max_length=13, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('valor_total', models.DecimalField(decimal_places=30, max_digits=30, verbose_name='Valor total')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Pendente', 'Pendente'), ('Fechado', 'Fechado')], default='Novo', max_length=255, verbose_name='Status')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('data_ini', models.DateField(verbose_name='Data')),
                ('visivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clinic')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medic')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('foto', models.ImageField(null=True, upload_to='static/img', verbose_name='Foto')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
            ],
        ),
    ]
