# Generated by Django 3.2.6 on 2021-11-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0004_auto_20211008_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='nome',
            new_name='titulo',
        ),
    ]
