# Generated by Django 3.2.6 on 2021-11-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nome_pipeline_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='produto',
            field=models.CharField(choices=[('nMonitor', 'nMonitor'), ('nSensor', 'nSensor'), ('nCommand', 'nCommand'), ('nEcho', 'nEcho'), ('nReport', 'nR'), ('Iara', 'Iara')], default=' ', max_length=255, verbose_name='Status'),
        ),
    ]
