# Generated by Django 3.2.6 on 2021-11-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211105_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='produto',
            field=models.CharField(choices=[('nMonitor', 'nMonitor'), ('nSensor', 'nSensor'), ('nCommand', 'nCommand'), ('nEcho', 'nEcho'), ('nReport', 'nReport'), ('Iara', 'Iara')], default=' ', max_length=255, verbose_name='Status'),
        ),
    ]
