# Generated by Django 3.2.6 on 2021-11-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211111_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='cargo',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
    ]
