# Generated by Django 3.2.6 on 2021-11-14 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_agent_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
