# Generated by Django 3.2.6 on 2021-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Empresa'),
        ),
    ]
