# Generated by Django 3.2.6 on 2021-11-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pipeline_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='clinica',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='medico',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medic'),
        ),
    ]
