# Generated by Django 3.2.6 on 2021-11-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20211123_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='clinica',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clinic'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='medico',
            field=models.ForeignKey(default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medic'),
        ),
    ]
