# Generated by Django 3.2.6 on 2021-11-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211123_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novo', models.CharField(default='Nova Proposta', max_length=25, verbose_name='Nova Proposta')),
                ('aberto', models.CharField(default='Primeiro Contato', max_length=25, verbose_name='Primeiro Contato')),
                ('pendente', models.CharField(default='Proposta em Andamento', max_length=25, verbose_name='Proposta em Andamento')),
                ('fechado', models.CharField(default='Proposta fechada', max_length=25, verbose_name='Proposta fechada')),
            ],
        ),
    ]
