# Generated by Django 3.2.6 on 2021-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211123_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulomain',
            name='aberto',
            field=models.CharField(default='Primeiro Contato', max_length=25, verbose_name='Primeiro Contato'),
        ),
        migrations.AlterField(
            model_name='titulomain',
            name='fechado',
            field=models.CharField(default='Proposta fechada', max_length=25, verbose_name='Proposta fechada'),
        ),
        migrations.AlterField(
            model_name='titulomain',
            name='novo',
            field=models.CharField(default='Nova Proposta', max_length=25, verbose_name='Nova Proposta'),
        ),
        migrations.AlterField(
            model_name='titulomain',
            name='pendente',
            field=models.CharField(default='Proposta em Andamento', max_length=25, verbose_name='Proposta em Andamento'),
        ),
    ]
